/**
 * Constants used across the YouTube Music Plus extension
 */

export const CONSTANTS = {
  PLAYER: {
    MAX_RETRIES: 10,
    RETRY_INTERVAL_MS: 1000,
    SEEK_DURATION_SECONDS: 10,
    SOURCE: {
      YOUTUBE: 'youtube',
      LOCAL: 'local'
    },
    STATE: {
      UNSTARTED: -1,
      ENDED: 0,
      PLAYING: 1,
      PAUSED: 2,
      BUFFERING: 3,
      CUED: 5
    }
  },
  UI: {
    STATUS_DURATION_MS: 3000,
    DEBOUNCE_DELAY_MS: 300,
    THROTTLE_LIMIT_MS: 300,
    UI_UPDATE_DELAY_MS: 500,
    ISSUE_URL: 'https://chromewebstore.google.com/detail/lkieghnbgfnidfhdeclkjkmnjokmkmdc/support',
    BUTTON_IDS: {
      FIND_UNAVAILABLE: 'findUnavailableBtn',
      FIND_VIDEO_TRACKS: 'findVideoTracksBtn',
      IMPORT_FROM_FOLDER: 'importFromFolderBtn',
      FIND_DUPLICATE_TRACKS: 'findDuplicateTracksBtn',
      LIST_ALL_TRACKS: 'listAllTracksBtn',
      IMPORT_FROM_FILE: 'importFromFileBtn',
      CANCEL_SEARCH: 'cancelSearchBtn',
      REPLACE_SELECTED: 'replaceSelectedBtn',
      ADD_SELECTED: 'addSelectedBtn',
      REMOVE_SELECTED: 'removeSelectedBtn',
      KEEP_ONLY_SELECTED: 'keepOnlySelectedBtn',
      IGNORE_GROUP: 'ignoreGroupBtn',
      FIND_REPLACE: 'findReplaceBtn',
      SYNC_PLAYLIST: 'syncPlaylistBtn',
      ADD_TO_PLAYLIST: 'addToPlaylistBtn',
      BACK_BUTTON: 'backButton',
      FIND_LOCAL_REPLACEMENTS: 'findLocalReplacementsBtn',
      IMPORT_FILE_INPUT: 'importFileInput',
      REFRESH_PLAYLISTS: 'refreshPlaylistsBtn',
      LOAD_ALL_PLAYLISTS: 'loadAllPlaylistsBtn',
      CLOSE_POPUP: 'closePopupBtn',
      MINIMIZE_POPUP: 'minimizePopupBtn',
      SELECT_TARGET_PLAYLIST: 'selectTargetPlaylistBtn',
      CANCEL_TARGET_SELECTION: 'cancelTargetSelectionBtn',
      REFRESH_TARGET_PLAYLISTS: 'refreshTargetPlaylistsBtn',
      LOAD_ALL_TARGET_PLAYLISTS: 'loadAllTargetPlaylistsBtn',
      CANCEL_TARGET_MODAL: 'cancelTargetModalBtn',
      CLOSE_TARGET_MODAL: 'closeTargetModalBtn',
    },
    ELEMENT_IDS: {
      PROGRESS_TEXT: 'progressText',
      SELECTION_FOOTER: 'ytMusicPlusSelectionFooter',
      ITEMS_GRID_CONTAINER: 'yt-music-plus-itemsGridContainer',
      GRID_HEADER_REPLACEMENT: 'gridHeaderReplacement',
      SEARCH_INPUT: 'ytMusicPlusSearchInput',
      CLEAR_SEARCH_BTN: 'ytMusicPlusClearSearchBtn',
      SEARCH_PROGRESS: 'searchProgress',
      PLAYLISTS_LOADING_INDICATOR: 'playlistsLoadingIndicator',
      PLAYLISTS_GRID: 'playlistsGrid',
      POPUP_TITLE: 'popupTitle',
      NAV_BTN: 'yt-music-plus-nav-btn',
      ACTION_BUTTONS: 'yt-music-plus-action-buttons',
      POPUP_HOLDER: 'yt-music-plus-popup',
      PLAYLIST_DETAILS_SCREEN: 'playlistDetailsScreen',
      PLAYLIST_SELECTION_SCREEN: 'playlistSelectionScreen',
      MAIN_POPUP: 'yt-music-plus-mainPopup',
      TARGET_PLAYLIST_NAME: 'targetPlaylistName',
      TARGET_PLAYLIST_CONTAINER: 'targetPlaylistContainer',
      TARGET_PLAYLIST_MODAL: 'targetPlaylistModal',
      TARGET_PLAYLISTS_GRID: 'targetPlaylistsGrid',
      TARGET_PLAYLISTS_LOADING: 'targetPlaylistsLoadingIndicator',
      PLAYLIST_SELECTION_ACTIONS: 'playlistSelectionActions',
      PLAYLIST_COUNTS: 'playlistCounts',
      TOTAL_PLAYLIST_COUNT: 'totalPlaylistCount',
      EDITABLE_PLAYLIST_COUNT: 'editablePlaylistCount',
      SELECTION_COUNT: 'selectionCount',
      MEDIA_ITEM_TEMPLATE: 'yt-music-plus-media-item-template',
      GRID_ROW_TEMPLATE: 'yt-music-plus-grid-row-template',
      PLAYLIST_CARD_TEMPLATE: 'yt-music-plus-playlist-card-template',
      PLAYLIST_THUMBNAIL: 'yt-music-plus-playlistThumbnail',
      PLAYLIST_NAME: 'yt-music-plus-playlistName',
      PLAYLIST_TRACK_COUNT: 'yt-music-plus-playlistTrackCount',
      PLAYLIST_DESCRIPTION: 'yt-music-plus-playlistDescription',
      ERROR_MESSAGE_TEMPLATE: 'yt-music-plus-error-message-template',
      NO_PLAYLISTS_TEMPLATE: 'yt-music-plus-no-playlists-template',
      SELECT_ALL_CHECKBOX: 'yt-music-plus-selectAllCheckbox',
      ACTION_BUTTONS_TEMPLATE: 'yt-music-plus-action-buttons-template',
      IGNORE_GROUP_BTN_TEMPLATE: 'yt-music-plus-ignore-group-btn-template',
      WARNING_MESSAGE: 'yt-music-plus-warningMessage',
      SELECT_ALL_CHECKBOX_ID: 'yt-music-plus-selectAllCheckbox',
      CLOSE_WARNING_BTN: 'closeWarningBtn',
      TOGGLE_GRID_BTN: 'toggleGridBtn',
    },
    CLASSES: {
      ACTIVE: 'active',
      HIDDEN: 'hidden',
      MINIMIZED: 'minimized',
      BTN_PRIMARY: 'btn-primary',
      BTN_SECONDARY: 'btn-secondary',
      BTN_DANGER: 'btn-danger',
      LIST_ONLY_MODE: 'list-only-mode',
      DUPLICATE_TRACK_MODE: 'duplicate-track-mode',
      ITEM_CHECKBOX: 'item-checkbox',
      GRID_ROW: 'grid-row',
      BTN: 'btn',
      PLAYLIST_ACTION_BUTTONS: 'playlist-action-buttons',
      ITEMS_GRID_WRAPPER: 'items-grid-wrapper',
      POPUP_CONTAINER: 'yt-music-extended-popup-container',
      POPUP_HEADER: 'popup-header',
      MEDIA_ITEM: 'media-item',
      MEDIA_THUMBNAIL: 'media-thumbnail',
      MEDIA_TITLE: 'media-title',
      MEDIA_ARTIST: 'media-artist',
      MEDIA_LINK: 'media-link',
      CONTROLS: 'yt-music-plus-controls',
      BTN_PLAY: 'btn-play',
      BTN_PAUSE: 'btn-pause',
      BTN_SEEK_BACK: 'btn-seek-back',
      BTN_SEEK_FORWARD: 'btn-seek-forward',
      MEDIA_INFO: 'media-info',
      GRID_COL_SERIAL: 'grid-col-serial',
      GRID_COL_ORIGINAL: 'grid-col-original',
      GRID_COL_REPLACEMENT: 'grid-col-replacement',
      POTENTIAL_MISMATCH: 'potential-mismatch',
      WARNING_ICON: 'warning-icon',
      ERROR_MESSAGE: 'error-message',
      PLAYLIST_CARD: 'playlist-card',
      PLAYLIST_CARD_THUMBNAIL: 'playlist-card-thumbnail',
      PLAYLIST_CARD_TITLE: 'playlist-card-title',
      PLAYLIST_CARD_META: 'playlist-card-meta',
      NO_PLAYLISTS_MESSAGE: 'no-playlists-message',
      COLLAPSED: 'collapsed',
      EXPANDED: 'expanded',
      PLAYLIST_INFO_SECTION: 'playlist-info-section',
      DUPLICATE_GROUP_START: 'duplicate-group-start',
      DUPLICATE_GROUP_ROW: 'duplicate-group-row',
      ALT_DUPLICATE_GROUP_ROW: 'alt-duplicate-group-row',
      IGNORE_GROUP_BTN: 'ignore-group-btn',
    },
    SELECTORS: {
      YT_MUSIC_HEADER: 'ytmusic-responsive-header-renderer',
      ITEMS_GRID_CHECKBOXES: '#yt-music-plus-itemsGridContainer .item-checkbox',
      ACTIVE_ACTION_BUTTON: '.playlist-action-buttons .btn.active',
      CONTROL_BTN: '.yt-music-plus-control-btn',
    },
    STRINGS: {
      SELECT_TARGET_TITLE: 'Select Target Playlist',
      PLAYLIST_FALLBACK: 'playlist',
      IMPORT_ADD_PROGRESS_PREFIX: 'Adding track',
      IMPORT_ADD_COMPLETED: 'All additions completed.',
    }
  },
  SETTINGS: {
    DEFAULT: {
      showNavButton: true,
      showPlaylistButton: true,
      loadAllPlaylists: false,
      autoListAllTracks: true,
      hideWarningMessage: false
    }
  },
  API: {
    INNERTUBE_ENDPOINT: 'https://music.youtube.com',
    PLAYLIST_BROWSE_IDS: [
      'FEmusic_liked_playlists',
      'FEmusic_library_landing'
    ],
    SIMILARITY_THRESHOLD: 0.5,
    JARO_WINKLER_PREFIX_LEN: 4,
    JARO_WINKLER_SCALING_FACTOR: 0.1,
    TIMEOUT_DURATION_MS: 100,
    PAGE_LOAD_TIMEOUT_MS: 3000,
    BASE_URL: 'https://music.youtube.com/watch?v=',
    PLAYLIST_PAGE_PATH: 'https://music.youtube.com/playlist',
  },
  PARSER: {
    FILTER_TEXTS: [', ', ' & ', ' - ', 'Song', 'Video', ' • '],
    EDIT_KEYWORDS: ['edit details', 'delete playlist', 'rename playlist', 'edit playlist'],
  },
  REGEX: {
    GENERIC_NAME: /^\d*\s*(?:-|_)?\s*(?:(?:unknown|untitled|misc)(?:\s*artist)?\s*(?:-|_)?\s*)?(?:track|audio\s*track|unknown|untitled|misc)\s*\d*$/i,
    VIDEO_SUFFIX: /(official\s*)?(music\s*)?video/gi,
  },
  MEDIA: {
    EXTENSIONS: ['.mp3', '.flac', '.m4a', '.ogg', '.wav', '.aac', '.wma', '.opus'],
  },
  STORAGE_KEYS: {
    // Add storage keys here if needed
  }
};
