/**
 * Constants used across the YouTube Music Plus extension
 */

export const CONSTANTS = {
  PLAYER: {
    MAX_RETRIES: 10,
    RETRY_INTERVAL_MS: 1000,
    SEEK_DURATION_SECONDS: 10,
    SOURCE: {
      YOUTUBE: 'youtube',
      LOCAL: 'local'
    },
    STATE: {
      UNSTARTED: -1,
      ENDED: 0,
      PLAYING: 1,
      PAUSED: 2,
      BUFFERING: 3,
      CUED: 5
    }
  },
  UI: {
    STATUS_DURATION_MS: 3000,
    DEBOUNCE_DELAY_MS: 300,
    THROTTLE_LIMIT_MS: 300,
    UI_UPDATE_DELAY_MS: 500,
    VIEW_MODES: {
      DEFAULT: 'DEFAULT',
      LIST_ALL: 'LIST_ALL',
      DUPLICATES: 'DUPLICATES',
      IMPORT: 'IMPORT',
      SEARCH_RESULTS: 'SEARCH_RESULTS'
    },
    ISSUE_URL: 'https://chromewebstore.google.com/detail/lkieghnbgfnidfhdeclkjkmnjokmkmdc/support',
    BUTTON_IDS: {
      FIND_UNAVAILABLE: 'yt-music-plus-findUnavailableBtn',
      FIND_VIDEO_TRACKS: 'yt-music-plus-findVideoTracksBtn',
      IMPORT_FROM_FOLDER: 'yt-music-plus-importFromFolderBtn',
      FIND_DUPLICATE_TRACKS: 'yt-music-plus-findDuplicateTracksBtn',
      LIST_ALL_TRACKS: 'yt-music-plus-listAllTracksBtn',
      IMPORT_FROM_FILE: 'yt-music-plus-importFromFileBtn',
      CANCEL_SEARCH: 'yt-music-plus-cancelSearchBtn',
      REPLACE_SELECTED: 'yt-music-plus-replaceSelectedBtn',
      ADD_SELECTED: 'yt-music-plus-addSelectedBtn',
      REMOVE_SELECTED: 'yt-music-plus-removeSelectedBtn',
      KEEP_ONLY_SELECTED: 'yt-music-plus-keepOnlySelectedBtn',
      IGNORE_GROUP: 'yt-music-plus-ignoreGroupBtn',
      FIND_REPLACE: 'yt-music-plus-findReplaceBtn',
      SYNC_PLAYLIST: 'yt-music-plus-syncPlaylistBtn',
      ADD_TO_PLAYLIST: 'yt-music-plus-addToPlaylistBtn',
      BACK_BUTTON: 'yt-music-plus-backButton',
      FIND_LOCAL_REPLACEMENTS: 'yt-music-plus-findLocalReplacementsBtn',
      IMPORT_FILE_INPUT: 'yt-music-plus-importFileInput',
      REFRESH_PLAYLISTS: 'yt-music-plus-refreshPlaylistsBtn',
      LOAD_ALL_PLAYLISTS: 'yt-music-plus-loadAllPlaylistsBtn',
      CLOSE_POPUP: 'yt-music-plus-closePopupBtn',
      MINIMIZE_POPUP: 'yt-music-plus-minimizePopupBtn',
      OPEN_SETTINGS: 'yt-music-plus-openSettingsLink',
      SELECT_TARGET_PLAYLIST: 'yt-music-plus-selectTargetPlaylistBtn',
      CANCEL_TARGET_SELECTION: 'yt-music-plus-cancelTargetSelectionBtn',
      REFRESH_TARGET_PLAYLISTS: 'yt-music-plus-refreshTargetPlaylistsBtn',
      LOAD_ALL_TARGET_PLAYLISTS: 'yt-music-plus-loadAllTargetPlaylistsBtn',
      CANCEL_TARGET_MODAL: 'yt-music-plus-cancelTargetModalBtn',
      CLOSE_TARGET_MODAL: 'yt-music-plus-closeTargetModalBtn',
    },
    ELEMENT_IDS: {
      PROGRESS_TEXT: 'yt-music-plus-progressText',
      SELECTION_FOOTER: 'yt-music-plus-selectionFooter',
      ITEMS_GRID_CONTAINER: 'yt-music-plus-itemsGridContainer',
      GRID_HEADER_REPLACEMENT: 'yt-music-plus-gridHeaderReplacement',
      SEARCH_INPUT: 'yt-music-plus-searchInput',
      CLEAR_SEARCH_BTN: 'yt-music-plus-clearSearchBtn',
      SEARCH_PROGRESS: 'yt-music-plus-searchProgress',
      PLAYLISTS_LOADING_INDICATOR: 'yt-music-plus-playlistsLoadingIndicator',
      PLAYLISTS_GRID: 'yt-music-plus-playlistsGrid',
      POPUP_TITLE: 'yt-music-plus-popupTitle',
      NAV_BTN: 'yt-music-plus-nav-btn',
      ACTION_BUTTONS: 'yt-music-plus-action-buttons',
      POPUP_HOLDER: 'yt-music-plus-popup',
      PLAYLIST_DETAILS_SCREEN: 'yt-music-plus-playlistDetailsScreen',
      PLAYLIST_SELECTION_SCREEN: 'yt-music-plus-playlistSelectionScreen',
      MAIN_POPUP: 'yt-music-plus-mainPopup',
      TARGET_PLAYLIST_NAME: 'yt-music-plus-targetPlaylistName',
      TARGET_PLAYLIST_CONTAINER: 'yt-music-plus-targetPlaylistContainer',
      TARGET_PLAYLIST_MODAL: 'yt-music-plus-targetPlaylistModal',
      TARGET_PLAYLISTS_GRID: 'yt-music-plus-targetPlaylistsGrid',
      TARGET_PLAYLISTS_LOADING: 'yt-music-plus-targetPlaylistsLoadingIndicator',
      PLAYLIST_SELECTION_ACTIONS: 'yt-music-plus-playlistSelectionActions',
      PLAYLIST_COUNTS: 'yt-music-plus-playlistCounts',
      TOTAL_PLAYLIST_COUNT: 'yt-music-plus-totalPlaylistCount',
      EDITABLE_PLAYLIST_COUNT: 'yt-music-plus-editablePlaylistCount',
      SELECTION_COUNT: 'yt-music-plus-selectionCount',
      MEDIA_ITEM_TEMPLATE: 'yt-music-plus-media-item-template',
      GRID_ROW_TEMPLATE: 'yt-music-plus-grid-row-template',
      PLAYLIST_CARD_TEMPLATE: 'yt-music-plus-playlist-card-template',
      PLAYLIST_THUMBNAIL: 'yt-music-plus-playlistThumbnail',
      PLAYLIST_NAME: 'yt-music-plus-playlistName',
      PLAYLIST_TRACK_COUNT: 'yt-music-plus-playlistTrackCount',
      PLAYLIST_DESCRIPTION: 'yt-music-plus-playlistDescription',
      ERROR_MESSAGE_TEMPLATE: 'yt-music-plus-error-message-template',
      NO_PLAYLISTS_TEMPLATE: 'yt-music-plus-no-playlists-template',
      SELECT_ALL_CHECKBOX: 'yt-music-plus-selectAllCheckbox',
      ACTION_BUTTONS_TEMPLATE: 'yt-music-plus-action-buttons-template',
      IGNORE_GROUP_BTN_TEMPLATE: 'yt-music-plus-ignore-group-btn-template',
      WARNING_MESSAGE: 'yt-music-plus-warningMessage',
      SELECT_ALL_CHECKBOX_ID: 'yt-music-plus-selectAllCheckbox',
      CLOSE_WARNING_BTN: 'yt-music-plus-closeWarningBtn',
      TOGGLE_GRID_BTN: 'yt-music-plus-toggleGridBtn',
      VERSION: 'yt-music-plus-version',
    },
    CLASSES: {
      ACTIVE: 'yt-music-plus-active',
      HIDDEN: 'yt-music-plus-hidden',
      MINIMIZED: 'yt-music-plus-minimized',
      BTN_PRIMARY: 'yt-music-plus-btn-primary',
      BTN_SECONDARY: 'yt-music-plus-btn-secondary',
      BTN_DANGER: 'yt-music-plus-btn-danger',
      LIST_ONLY_MODE: 'yt-music-plus-list-only-mode',
      DUPLICATE_TRACK_MODE: 'yt-music-plus-duplicate-track-mode',
      ITEM_CHECKBOX: 'yt-music-plus-item-checkbox',
      GRID_ROW: 'yt-music-plus-grid-row',
      BTN: 'yt-music-plus-btn',
      NAV_BAR_BTN: 'yt-music-plus-nav-bar-btn',
      PLAYLIST_ACTION_BUTTONS: 'yt-music-plus-playlist-action-buttons',
      ITEMS_GRID_WRAPPER: 'yt-music-plus-items-grid-wrapper',
      POPUP_CONTAINER_HOLDER: 'yt-music-plus-popup-container-holder',
      POPUP_CONTAINER: 'yt-music-plus-popup-container',
      POPUP_HEADER: 'yt-music-plus-popup-header',
      MEDIA_ITEM: 'yt-music-plus-media-item',
      MEDIA_THUMBNAIL: 'yt-music-plus-media-thumbnail',
      MEDIA_TITLE: 'yt-music-plus-media-title',
      MEDIA_ARTIST: 'yt-music-plus-media-artist',
      MEDIA_LINK: 'yt-music-plus-media-link',
      CONTROLS: 'yt-music-plus-controls',
      BTN_PLAY: 'yt-music-plus-btn-play',
      BTN_PAUSE: 'yt-music-plus-btn-pause',
      BTN_SEEK_BACK: 'yt-music-plus-btn-seek-back',
      BTN_SEEK_FORWARD: 'yt-music-plus-btn-seek-forward',
      MEDIA_INFO: 'yt-music-plus-media-info',
      GRID_COL_SERIAL: 'yt-music-plus-grid-col-serial',
      GRID_COL_ORIGINAL: 'yt-music-plus-grid-col-original',
      GRID_COL_REPLACEMENT: 'yt-music-plus-grid-col-replacement',
      POTENTIAL_MISMATCH: 'yt-music-plus-potential-mismatch',
      WARNING_CONTAINER: 'yt-music-plus-warning-container',
      WARNING_ICON: 'yt-music-plus-warning-icon',
      WARNING_MESSAGE_TEXT: 'yt-music-plus-warning-message-text',
      ERROR_MESSAGE: 'yt-music-plus-error-message',
      PLAYLIST_CARD: 'yt-music-plus-playlist-card',
      PLAYLIST_CARD_THUMBNAIL: 'yt-music-plus-playlist-card-thumbnail',
      PLAYLIST_CARD_TITLE: 'yt-music-plus-playlist-card-title',
      PLAYLIST_CARD_META: 'yt-music-plus-playlist-card-meta',
      NO_PLAYLISTS_MESSAGE: 'yt-music-plus-no-playlists-message',
      COLLAPSED: 'yt-music-plus-collapsed',
      EXPANDED: 'yt-music-plus-expanded',
      PLAYLIST_INFO_SECTION: 'yt-music-plus-playlist-info-section',
      DUPLICATE_GROUP_START: 'yt-music-plus-duplicate-group-start',
      DUPLICATE_GROUP_ROW: 'yt-music-plus-duplicate-group-row',
      ALT_DUPLICATE_GROUP_ROW: 'yt-music-plus-alt-duplicate-group-row',
      IGNORE_GROUP_BTN: 'yt-music-plus-ignore-group-btn',
      SELECT_ALL_CHECKBOX: 'yt-music-plus-select-all-checkbox',
    },
    SELECTORS: {
      YT_MUSIC_HEADER: 'ytmusic-responsive-header-renderer',
      ITEMS_GRID_CHECKBOXES: '#yt-music-plus-itemsGridContainer .yt-music-plus-item-checkbox',
      ACTIVE_ACTION_BUTTON: '.yt-music-plus-playlist-action-buttons .yt-music-plus-btn.yt-music-plus-active',
      CONTROL_BTN: '.yt-music-plus-control-btn',
    },
    STRINGS: {
      SELECT_TARGET_TITLE: 'Select Target Playlist',
      PLAYLIST_FALLBACK: 'playlist',
      ALREADY_IN_PLAYLIST: 'Existing',
      POTENTIAL_MISMATCH: 'Mismatch',
      IMPORT_ADD_PROGRESS_PREFIX: 'Adding track',
      IMPORT_ADD_COMPLETED: 'All additions completed.',
    }
  },
  SETTINGS: {
    DEFAULT: {
      showNavButton: true,
      showPlaylistButton: true,
      loadAllPlaylists: false,
      autoListAllTracks: true,
      hideWarningMessage: false
    }
  },
  API: {
    INNERTUBE_ENDPOINT: 'https://music.youtube.com',
    PLAYLIST_BROWSE_IDS: [
      'FEmusic_liked_playlists',
      'FEmusic_library_landing'
    ],
    SIMILARITY_THRESHOLD: 0.5,
    JARO_WINKLER_PREFIX_LEN: 4,
    JARO_WINKLER_SCALING_FACTOR: 0.1,
    TIMEOUT_DURATION_MS: 100,
    PAGE_LOAD_TIMEOUT_MS: 3000,
    BASE_URL: 'https://music.youtube.com/watch?v=',
    PLAYLIST_PAGE_PATH: 'https://music.youtube.com/playlist',
  },
  PARSER: {
    FILTER_TEXTS: [', ', ' & ', ' - ', 'Song', 'Video', ' • '],
    EDIT_KEYWORDS: ['edit details', 'delete playlist', 'rename playlist', 'edit playlist'],
  },
  REGEX: {
    GENERIC_NAME: /^\d*\s*(?:-|_)?\s*(?:(?:unknown|untitled|misc)(?:\s*artist)?\s*(?:-|_)?\s*)?(?:track|audio\s*track|unknown|untitled|misc)\s*\d*$/i,
    VIDEO_SUFFIX: /(official\s*)?(music\s*)?video/gi,
  },
  MEDIA: {
    EXTENSIONS: ['.mp3', '.flac', '.m4a', '.ogg', '.wav', '.aac', '.wma', '.opus'],
  },
  STORAGE_KEYS: {
    // Add storage keys here if needed
  }
};
